# Generated by Django 4.1.7 on 2023-05-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Name News', max_length=50, verbose_name='Name')),
                ('anons', models.CharField(default='Anons', max_length=250, verbose_name='Anons')),
                ('full_text', models.TextField(verbose_name='News Text')),
                ('date', models.DateTimeField(verbose_name='Date published')),
            ],
        ),
    ]
